### ISSUE TITLE
lillie.test or KScorrect?

### ISSUE THREAD

**Issue by Andrey-SR** [pnovack-gottshall/KScorrect#8]
What makes the lillie.test function different from the KScorrect package?

**Comment by pnovack-gottshall** [comment]
lillie.test() in package 'nortest' only tests a sample for the Normal distribution. lcKS() in 'KScorrect' also allows tests for Normal but also allows implementation for lognormal, uniform, loguniform, mixture of Normals, Weibull, gamma, and exponential distributions.
